// websocket/constants.js

export const SOCKET_NAMESPACE = {
  INTERVIEW: "INTERVIEW",
  RTC: "RTC",
  WORKSPACE: "WORKSPACE",
  TERMINAL: "TERMINAL",
  CHAT: "CHAT",
};

export const INTERVIEW_EVENTS = {
  JOIN_ROOM: "JOIN_ROOM",

  LEAVE_ROOM: "LEAVE_ROOM",

  PARTICIPANT_JOINED: "PARTICIPANT_JOINED",

  PARTICIPANT_LEFT: "PARTICIPANT_LEFT",

  INTERVIEW_READY: "INTERVIEW_READY",

  INTERVIEW_LIVE: "INTERVIEW_LIVE",
};

export const ROOM_STATUS = {
  WAITING: "WAITING",
  READY: "READY",
  LIVE: "LIVE",
  ENDED: "ENDED",
};
