// websocket/constants.js
export const SOCKET_NAMESPACE = {
  INTERVIEW: "INTERVIEW",
  RTC: "RTC",
  WORKSPACE: "WORKSPACE",
  TERMINAL: "TERMINAL",
  CHAT: "CHAT",
  ERROR: "ERROR"
};

export const INTERVIEW_EVENTS = {
  JOIN_ROOM: "JOIN_ROOM",

  LEAVE_ROOM: "LEAVE_ROOM",
  JOIN_ROOM_ACK: "JOIN_ROOM_ACK",
  PARTICIPANT_JOINED: "PARTICIPANT_JOINED",

  PARTICIPANT_LEFT: "PARTICIPANT_LEFT",

  INTERVIEW_READY: "INTERVIEW_READY",

  INTERVIEW_LIVE: "INTERVIEW_LIVE",
  INTERVIEW_ENDED: "INTERVIEW_ENDED",
};

export const RTC_EVENTS = {
  OFFER: "OFFER",
  ANSWER: "ANSWER",
  ICE_CANDIDATE: "ICE_CANDIDATE"
}

export const ROOM_STATUS = {
  WAITING: "WAITING",
  READY: "READY",
  LIVE: "LIVE",
  ENDED: "ENDED",
};
